trigger:
  branches:
    include:
      - main
pool:
  vmImage: ubuntu-latest

steps:
  - task: DownloadSecureFile@1
    name: sshKey
    inputs:
      secureFile: "id_rsa.pub"

  - script: |
      mkdir -p ~/.ssh
      cp $(sshKey.secureFilePath) ~/.ssh/id_rsa
      chmod 600 ~/.ssh/id_rsa
      ssh -o StrictHostKeyChecking=no user@your-vm-ip "cd ~/websites/test && git pull origin main"
    displayName: "SSH into VM and Pull Latest Code"
